FROM python:3.9-slim
LABEL maintainer="devonchoucs@gmail.com"

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /tmp/requirements.txt
COPY ./requirements.dev.txt /tmp/requirements.dev.txt
COPY ./app /app
WORKDIR /app
EXPOSE 8000

ARG DEV=false
RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apt-get update && \
    apt-get install -y --no-install-recommends gcc libc-dev && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    if [ $DEV = "true" ]; \
        then /py/bin/pip install -r /tmp/requirements.dev.txt ;  \
    fi && \
    apt-get purge -y --auto-remove gcc libc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp

RUN adduser \
        --disabled-password \
        django-user

ENV PATH="/py/bin:$PATH"

USER django-user