version: "3"

services:
  express-api:
    build:
      context: ./express-api
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./express-api:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  django-api:
    build:
      context: ./django-api
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./django-api/app:/app
    command: >
      uwsgi --http :8000 --workers 4 --master --enable-threads --module app.wsgi

volumes:
  dev-db-data: