version: "3"

services:
  express-api:
    build:
      context: ./express-api
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./express-api:/app
      - /app/node_modules
    command: npm run start.dev
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  dev-db-data: