FROM nginxinc/nginx-unprivileged:1-alpine
LABEL maintainer="devonchoucs@gmail.com"

COPY ./default.conf.tpl /etc/nginx/default.conf.tpl
COPY ./run.sh /run.sh

ENV LISTEN_PORT=8000
ENV API_HOST=express-api
ENV API_PORT=3000

USER root

RUN touch /etc/nginx/conf.d/default.conf && \
    chown nginx:nginx /etc/nginx/conf.d/default.conf && \
    chmod +x /run.sh

USER nginx

CMD ["/run.sh"]